steps:
  - label: ":rocket: Build and ship"
    commands: 
      - export CLOUDFLARE_ACCOUNT_ID="\$(buildkite-agent secret get CLOUDFLARE_ACCOUNT_ID)"
      - export CLOUDFLARE_API_TOKEN="\$(buildkite-agent secret get CLOUDFLARE_API_TOKEN)"
      - npm install
      - npm run deploy